spring.application.name=RetailRewardsApi
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:rewarddb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# --- THE FIX FOR MISSING DATA ---
# 1. Force Spring to run the SQL files
spring.sql.init.mode=always
# 2. Stop Hibernate from deleting your tables on startup
spring.jpa.hibernate.ddl-auto=none
# 3. Ensure data.sql runs AFTER the tables are ready
spring.jpa.defer-datasource-initialization=true
# Configurable Reward Business Logic
reward.threshold.tier1=50
reward.threshold.tier2=100
reward.multiplier.tier2=2